<!DOCTYPE html>
<html lang="uk">
<head>
    <title>Тема 15. Обробка винятків</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <link rel="stylesheet" href="../../../core/styles/styles.css">
    <style>
        .shower {
            --slide-ratio: calc(16 / 9);
        }
    </style>
</head>
<body class="shower list">

<header class="caption">
    <h1>Тема 15. Обробка винятків</h1>
</header>

<section class="slide">
    <h2>Тема 15. Обробка винятків</h2>
    <ol>
        <li>Що таке виняток</li>
        <li>Конструкція try catch</li>
        <li>Блок finally</li>
        <li>Використання throw</li>
        <li>Створення винятків користувача</li>
    </ol>
</section>

<section class="slide">
    <h2>Вивчивши матеріал даної теми, студент зможе:</h2>
    <ul>
        <li>Розуміти, що таке виняток.</li>
        <li>Розуміти різницю між помилкою етапу виконання та синтаксичною помилкою.</li>
        <li>Працювати із оператором try catch.</li>
        <li>Використовувати оператора finally.</li>
        <li>Використовувати оператор throw для генерації винятків користувача.</li>
        <li>Створювати типи винятків.</li>
    </ul>
</section>

<section class="slide">
    <h2>Що таке виняток</h2>
    <p><b>Винятки</b> – несподівані події, що переривають нормальну роботу коду та виникають під час виконання
        сценарію.</p>
    <p>Наприклад, спроба десеріалізувати об'єкт з рядка JSON, який містить помилку, призведе
        до виключення. Оскільки функція JSON.parse повинна повернути об'єкт, але не може
        цього зробити через неправильні вхідні дані, вона викидає виняток (генерує помилку), яка
        зупиняє подальше виконання сценарію. Якщо parse не може повернути дані, немає сенсу
        у виконанні подальшого коду, тільки якщо розробник не передбачає альтернативного
        алгоритму та опрацює виняткову ситуацію.</p>
</section>

<section class="slide">
    <h2>Що таке виняток</h2>
    <p>Обробка виключення здійснюється за допомогою ключових слів: <b>try, catch, finally</b></p>
    <p><b>Можливі конструкції у коді:</b></p>
    <img src="images/1.png" alt="" width="100%">
</section>

<section class="slide">
    <h2>try/catch</h2>
    <div class="columns two">
        <div>
            <ul style="padding-top: 30px;">
                <li>Код, де під час виконання може бути
                    помилка (виключення - exception).
                </li>
                <li>
                    Код, що обробляє виняток (якщо
                    виняток виникне).
                </li>
            </ul>
        </div>
        <div>
            <img src="images/2.png" alt="" width="100%">
        </div>
    </div>
    <p style="font-size: 17px; margin-top: 30px;">Якщо виняток генерується в коді, що знаходиться в блоці try, виняток
        припиняє виконання
        всіх наступних інструкцій у блоці try і переносить виконання в блок catch. При цьому
        інформація про помилку передається як параметр в блок catch. Після блоку catch сценарій
        продовжується. Якщо виняток виникає поза блоку catch — припиняється виконання
        всього сценарію.</p>
</section>

<section class="slide">
    <h2>Error (Основні конструктори помилок)</h2>
    <p style="font-size: 15px;">Об'єкт винятку містить три основні властивості:
        <b>name</b>
        — назва виключення,
        <b>message</b>
        —
        опис помилки, що виникла і
        <b>stack</b>
        — список викликів, які призвели до виключення.
    </p>
    <div class="columns three">
        <div style="align-self: center">
            <img src="images/3.png" alt="" width="100%">
        </div>
        <div style="font-size: 16px;">
            <ul>
                <li><b style="display: block">Error</b>
                    помилка під час виконання
                </li>
                <li><b style="display: block">EvalError</b>
                    помилка під час виконання
                    функції eval
                </li>
                <li><b style="display: block">RangeError</b>
                    значення виходить за діапазон
                </li>
                <li><b style="display: block">ReferenceError</b>
                    звернення до неіснуючої змінної
                </li>
            </ul>
        </div>
        <div style="font-size: 16px;">
            <ul>
                <li><b style="display: block">SyntaxError</b>
                    синтаксична помилка при виконанні коду
                    функції eval
                </li>
                <li><b style="display: block">TypeError</b>
                    неприпустимий тип для змінної або
                    параметра
                </li>
                <li><b style="display: block">URIError</b>
                    неприпустимі параметри для функції
                    encodeURI та decodeURI
                </li>
            </ul>
        </div>
    </div>
    <p style="color: #cc0000">Приклади 001 - 004 з директорії js/1-15-exception-handling/examples</p>
</section>

<section class="slide">
    <h2>Call stack</h2>
    <div class="columns two">
        <div>
            <img src="images/4.png" alt="" width="100%">
        </div>
        <div>
            <b>Стек виклику:</b>
            <ul>
                <li>at JSON.parse (&lt;anonymous&gt;) - саме тут з'явилась помилка</li>
                <li>at func3 (filename.html:25)</li>
                <li>at func2 (filename.html:18)</li>
                <li>at func1 (filename.html:14)</li>
                <li>at filename.html:31</li>
            </ul>
        </div>
    </div>
</section>

<section class="slide">
    <h2>Блок finally</h2>
    <p style="font-size: 18px;"><b>Finally</b> — блок коду, який гарантовано виконується. Finally може слідувати відразу
        за
        блоком try або за блоком catch. Якщо під час виконання відбувається виняток у блоці try,
        спрацьовує блок catch і після цього виконується блок finally. Якщо у блоці try не
        відбулося виключення, блок catch ігнорується, але finally все одно виконується. Якщо у
        блоці catch відбудеться ще один виняток або до блоку finally виконається оператор
        return, блок finally все одно виконається.</p>
    <p style="font-size: 18px;"><b>Finally</b> використовують для тих випадків, коли потрібно гарантувати виконання дії
        за
        будь-яких обставин. Наприклад, коли це операція, пов'язана зі звільненням ресурсів,
        виділених під час виконання блоку try.</p>
    <p style="color: #cc0000">Приклади 005, 006 з директорії js/1-15-exception-handling/examples</p>
</section>

<section class="slide">
    <h2>Використання throw</h2>
    <p>
        <b>Throw</b> оператор, який використовується для створення винятку.
    </p>
    <p>Якщо цей оператор
        виконується в коді, створений виняток за стеком виклику передається до тих пір, поки не
        потрапить до блоку catch або поки не закінчаться адреси в стеку викликів. </p>
    <p>
        Цей оператор
        має сенс використовувати для бібліотечних функцій, які використовуються в різних
        частинах програми та повинні повідомляти розробника про неправильне використання.
    </p>
    <p style="color: #cc0000">Приклади 007 - 008 з директорії js/1-15-exception-handling/examples</p>
</section>

<section class="slide">
    <h2>Створення винятків користувача</h2>
    <p>Для створення типу виключення, потрібно визначити новий клас і розширити один із
        системних класів винятків. За необхідністю визначити додаткові властивості та
        проініціалізувати властивості, отримані у спадок від класу батька.
    </p>
    <p>Після ключового слова throw може використовуватися будь-який об'єкт або просте
        значення, яке буде виключенням. Але браузер та інструменти для роботи з винятками
        можуть дати більше інформації та будуть зручними у використанні, якщо об'єкт помилки
        буде похідним від вбудованого класу помилки</p>
    <p style="color: #cc0000">Приклад 10 з директорії js/1-15-exception-handling/examples</p>
</section>

<section class="slide">
    <h2>Підсумки</h2>
    <ul>
        <li><b>Виняток</b> – несподівана подія, що перериває нормальну роботу коду та виникає під час виконання
            сценарію.
        </li>
        <li><b>try</b> – блок коду, у якому може виникнути виняток.</li>
        <li><b>catch</b> – блок коду, у якому виконуватиметься обробка виключення.</li>
        <li><b>finally</b> – блок коду, який гарантовано виконується незалежно від того, виник виняток чи ні.</li>
        <li><b>stack</b> – властивість об'єкта виключення, що містить список дзвінків, виконаних до виключення.</li>
        <li><b>throw</b> – ключове слово створення винятку в сценарії. Часто використовується в коді, який
            використовуватимуть інші розробники.
        </li>
    </ul>
</section>

<section class="slide">
    <h2>Контрольні питання</h2>
    <ol>
        <li>Що таке виняток? Наведіть приклад, коли у програмі виникає виняток.</li>
        <li>Як працює блок try/catch?</li>
        <li>Назвіть основні властивості об'єкта виключення.</li>
        <li>Що таке finally? Опишіть принцип роботи цього блоку.</li>
        <li>Як створити тип виключення користувача?</li>
    </ol>
</section>

<section class="slide">
    <h2 class="shout">Дякую за увагу!</h2>
</section>

<div class="progress"></div>

<script src="../../../core/shower.js"></script>
</body>
</html>

